name: Build Release
on:
  create:
    tags:
      - v*
jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: OpenDGLab Core ${{ steps.get_version.outputs.version }}
          body: |
            OpenDGLab Core ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
  gradle:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    needs: [create_release]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Allow Gradle Wrapper
      if: matrix.os == 'macos-latest'
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew assemble
    - name: Packaging Linux x64
      if: matrix.os == 'windows-latest'
      uses: papeloto/action-zip@v1
      with: 
        files: build/bin/linuxX64/
        dest: OpenDGLab-Core-Linux-X64.zip
    - name: Packaging Linux arm64
      if: matrix.os == 'windows-latest'
      uses: papeloto/action-zip@v1
      with: 
        files: build/bin/linuxArm64
        dest: OpenDGLab-Core-Linux-Arm64.zip
    - name: Packaging Windows x86
      if: matrix.os == 'windows-latest'
      uses: papeloto/action-zip@v1
      with: 
        files: build/bin/winX86
        dest: OpenDGLab-Core-Windows-X86.zip
    - name: Packaging Windows x86
      if: matrix.os == 'windows-latest'
      uses: papeloto/action-zip@v1
      with: 
        files: build/bin/winX64
        dest: OpenDGLab-Core-Windows-X64.zip
    - name: Packaging MacOS x64
      if: matrix.os == 'macos-latest'
      uses: papeloto/action-zip@v1
      with: 
        files: build/bin/macosX64
        dest: OpenDGLab-Core-MacOS-X64.zip
    - name: Upload Release Asset Linux x64
      uses: actions/upload-release-asset@v1
      if: matrix.os == 'windows-latest'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./OpenDGLab-Core-Linux-X64.zip
        asset_name: OpenDGLab-Core-Linux-X64.zip
        asset_content_type: application/zip
    - name: Upload Release Asset Linux arm64
      uses: actions/upload-release-asset@v1
      if: matrix.os == 'windows-latest'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./OpenDGLab-Core-Linux-Arm64.zip
        asset_name: OpenDGLab-Core-Linux-Arm64.zip
        asset_content_type: application/zip
    - name: Upload Release Asset Windows x86
      uses: actions/upload-release-asset@v1
      if: matrix.os == 'windows-latest'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./OpenDGLab-Core-Windows-X86.zip
        asset_name: OpenDGLab-Core-Windows-X86.zip
        asset_content_type: application/zip
    - name: Upload Release Asset Windows x64
      uses: actions/upload-release-asset@v1
      if: matrix.os == 'windows-latest'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./OpenDGLab-Core-Windows-X64.zip
        asset_name: OpenDGLab-Core-Windows-X64.zip
        asset_content_type: application/zip
    - name: Upload Release Asset MacOS x64
      uses: actions/upload-release-asset@v1
      if: matrix.os == 'macos-latest'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./OpenDGLab-Core-MacOS-X64.zip
        asset_name: OpenDGLab-Core-MacOS-X64.zip
        asset_content_type: application/zip